global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  #api service
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9000' ]
        labels:
          application: 'Api Gateway'

  # Product Service Metrics
  - job_name: 'product-service'
    metrics_path:
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Product Service'

  # Order Service Metrics
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Order Service'

  # Inventory Service Metrics
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'Inventory Service'

  # Notification Service Metrics
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'Notification Service'
